userauth_project/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import signup_view, login_view, patient_dashboard, doctor_dashboard

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('patient-dashboard/', patient_dashboard, name='patient_dashboard'),
    path('doctor-dashboard/', doctor_dashboard, name='doctor_dashboard'),
    #  path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
]

userauth_project/userauth_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Django login/logout
    path('', include('accounts.urls')),                      # Custom routes
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

userauth_project/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = (
        ('patient', 'Patient'),
        ('doctor', 'Doctor'),
    )
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES)
    profile_picture = models.ImageField(upload_to='profiles/', null=True, blank=True)
    address_line1 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    pincode = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return self.username

userauth_project/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    profile_picture = forms.ImageField(required=False)
    address_line1 = forms.CharField(required=True)
    city = forms.CharField(required=True)
    state = forms.CharField(required=True)
    pincode = forms.CharField(required=True, max_length=6)
    user_type = forms.ChoiceField(choices=CustomUser.USER_TYPE_CHOICES)

    class Meta:
        model = CustomUser
        fields = [
            'first_name', 'last_name', 'username', 'email',
            'password1', 'password2',
            'user_type', 'profile_picture',
            'address_line1', 'city', 'state', 'pincode'
        ]

userauth_project/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
from .models import CustomUser

def signup_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()

            raw_password = form.cleaned_data.get('password1')
            user = authenticate(request, username=user.username, password=raw_password)
            print(user)
            if user is not None:
                login(request, user)
                messages.success(request, 'Signup successful!')

                if user.user_type == 'patient':
                    return render(request ,'accounts/patient_dashboard.html', {'first_name': user.first_name, 'last_name': user.last_name, 'email' : user.email, 'address_line1': user.address_line1, 'city' : user.city, 'state': user.state , 'pincode': user.pincode})
                elif user.user_type == 'doctor':
                    return render(request, 'accounts/doctor_dashboard.html', {'first_name': user.first_name, 'last_name': user.last_name, 'email' : user.email, 'address_line1': user.address_line1, 'city' : user.city, 'state': user.state , 'pincode': user.pincode})
            else:
                messages.error(request, "Login after signup failed.")
        else:
            messages.error(request, 'Signup failed. Please fix the errors.')
    else:
        form = CustomUserCreationForm()

    return render(request, 'accounts/signup.html', {'user_form': form,
    'profile_form': form,})



def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.user_type == 'patient':
                return render(request ,'accounts/patient_dashboard.html', {'first_name': user.first_name, 'last_name': user.last_name, 'email' : user.email, 'address_line1': user.address_line1, 'city' : user.city, 'state': user.state , 'pincode': user.pincode})
            elif user.user_type == 'doctor':
                return render(request, 'accounts/doctor_dashboard.html', {'first_name': user.first_name, 'last_name': user.last_name, 'email' : user.email, 'address_line1': user.address_line1, 'city' : user.city, 'state': user.state , 'pincode': user.pincode})
        else:
            messages.error(request, 'Invalid username or password')
    return render(request, 'accounts/login.html')

@login_required
def patient_dashboard(request):
    return render(request, 'accounts/patient_dashboard.html')

@login_required
def doctor_dashboard(request):
    return render(request, 'accounts/doctor_dashboard.html')

userauth_project/accounts/templates/accounts/doctor_dashboard.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Doctor Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <!-- Google Fonts -->
    <!-- <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container mt-5">
    <h2>Wekcome Doctor</h2>
    <p><strong>Name:</strong> {{ first_name }} {{ last_name }}</p>
    <p><strong>Email:</strong> {{ email }}</p>
    <p><strong>Address:</strong> {{ address_line1 }}, {{ city }}, {{ state }} - {{ pincode }}</p>
    <br>
    <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>

</div>
</body>
</html>

userauth_project/accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <div class="card shadow p-4">
        <h2 class="text-center mb-4">Login</h2>

        {% if messages %}
        <div class="alert alert-danger">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            <div class="form-group mb-3">
                <label for="username">Username</label>
                <input type="text" name="username" class="form-control" placeholder="Enter username" required>
            </div>

            <div class="form-group mb-4">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" placeholder="Enter password" required>
            </div>

            <button type="submit" class="btn btn-primary w-100">Login</button>
        </form>
        <p class="mt-3">Don't have an account? <a href="/signup">Sign up here</a></p>

    </div>
</div>
</body>
</html>

userauth_project/accounts/templates/accounts/patient_dashboard.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Patient Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <!-- Google Fonts -->
    <!-- <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet"> -->

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container mt-5">
    <h2>Welcome Patient</h2>
    <p><strong>Name:</strong> {{ first_name }} {{ last_name }}</p>
    <p><strong>Email:</strong> {{ email }}</p>
    <p><strong>Address:</strong> {{ address_line1 }}, {{ city }}, {{ state }} - {{ pincode }}</p>
    <br>
    <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>

</div>
</body>
</html>

userauth_project/accounts/templates/accounts/signup.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Signup</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
  <div class="container mt-5">
    <h2>Signup</h2>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
     
        <!-- Non-field (general) errors -->
        {% if user_form.non_field_errors %}
          <div class="alert alert-danger">
            {% for error in user_form.non_field_errors %}
              <div>{{ error }}</div>
            {% endfor %}
          </div>
        {% endif %}

      <!-- User Info -->


      <div class="form-group mb-3">
        <label for="id_first_name">First Name</label>
        {{ user_form.first_name }}
        {% if user_form.first_name.errors %}
            <ul class="errorlist">
                {% for error in user_form.first_name.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
      </div>

      <div class="form-group mb-3">
        <label for="id_last_name">Last Name</label>
        {{ user_form.last_name }}

        {% if user_form.last_name.errors %}
          <ul class="errorlist">
            {% for error in user_form.last_name.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}

      </div>

      <div class="form-group mb-3">
        <label for="id_username">Username</label>
        {{ user_form.username }}
        {% if user_form.username.errors %}
          <ul class="errorlist">
            {% for error in user_form.username.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group mb-3">
        <label for="id_email">Email</label>
        {{ user_form.email }}
        {% if user_form.email.errors %}
          <ul class="errorlist">
            {% for error in user_form.email.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>


            <div class="form-group mb-3">
        <label for="id_password1">Password</label>
        {{ user_form.password1 }}
        {% if user_form.password1.errors %}
          <ul class="errorlist">
            {% for error in user_form.password1.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group mb-3">
        <label for="id_password2">Confirm Password</label>
        {{ user_form.password2 }}
        {% if user_form.password2.errors %}
          <ul class="errorlist">
            {% for error in user_form.password2.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>


      <!-- Profile Info -->
      

      <div class="form-group mb-3">
        <label for="id_user_type">User Type</label>
        {{ profile_form.user_type }}
        {% if profile_form.user_type.errors %}
          <ul class="errorlist">
            {% for error in profile_form.user_type.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>


      <div class="form-group mb-3">
        <label for="id_profile_picture">Profile Picture</label>
        {{ profile_form.profile_picture }}
        {% if profile_form.profile_picture.errors %}
          <ul class="errorlist">
            {% for error in profile_form.profile_picture.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <!-- Address -->
      <div class="form-group mb-3">
        <label for="id_address_line1">Address Line 1</label>
        {{ profile_form.address_line1 }}
        {% if profile_form.address_line1.errors %}
          <ul class="errorlist">
            {% for error in profile_form.address_line1.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>


      <div class="form-group mb-3">
        <label for="id_city">City</label>
        {{ profile_form.city }}
        {% if profile_form.city.errors %}
          <ul class="errorlist">
            {% for error in profile_form.city.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>


      <div class="form-group mb-3">
        <label for="id_state">State</label>
        {{ profile_form.state }}
        {% if profile_form.state.errors %}
          <ul class="errorlist">
            {% for error in profile_form.state.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>


      <div class="form-group mb-3">
        <label for="id_pincode">Pincode</label>
        {{ profile_form.pincode }}
        {% if profile_form.pincode.errors %}
          <ul class="errorlist">
            {% for error in profile_form.pincode.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group mt-4">
        <button type="submit" class="btn btn-primary">Sign Up</button>
      </div>
    </form>
    
<p>Already have an account? <a href="{% url 'login' %}">Login here</a></p>

  </div>
</body>
</html>